### ISSUE TITLE
npm ERR! missing script: size-install

### ISSUE THREAD

**Issue by sagar-gavhane** [andresz1/size-limit-action#10]
Hey, I'm getting an error about missing script: `size-install` but why we really need this script. I've tried to use `install: false` but it's not working.

This is my workflow.yml file

```yml
name: size
on:
  pull_request:
    branches:
      - master
jobs:
  size:
    runs-on: ubuntu-latest
    env:
      CI_JOB_NUMBER: 1
    steps:
      - uses: actions/checkout@v1
      - uses: andresz1/size-limit-action@v1.1.0
        with:
          install: false
          github_token: ${{ secrets.GITHUB_TOKEN }}
```

This is an error message.
```
  with:
    install: false
    github_token: ***
  env:
    CI_JOB_NUMBER: 1
/usr/local/bin/npm run size-install
npm ERR! missing script: size-install

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2020-04-05T01_28_14_524Z-debug.log
```
