### ISSUE TITLE
bug: can't use action w/ bun. action trying to use npm

### ISSUE THREAD

**Issue by scffs** [andresz1/size-limit-action#114]
![image](https://github.com/andresz1/size-limit-action/assets/67464545/1631f2a0-03d8-43de-8e1c-f9afae0f85a1)

yml
```yml
name: Size Limit
on:
  pull_request:
    branches:
      - master
      - main
permissions:
  pull-requests: write
jobs:
  size:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 'latest'

      - uses: andresz1/size-limit-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          package_manager: bun
          script: bun size-limit:web
```

Example https://github.com/Diary-SPO/test/pull/2
