### ISSUE TITLE
master always reporting as 0 bytes, 0 sec, etc.

### ISSUE THREAD

**Issue by mhuggins** [andresz1/size-limit-action#123]
I just added the size-limit package and size-limit-action to our repo, and all new PRs are showing master as having a 0 byte size, 0 ms load/run time, etc.

<img width="816" alt="Image" src="https://github.com/user-attachments/assets/1e1f80fc-feb0-4daf-bcb3-27c496afe91a" />

Our configuration is nothing crazy, there's not much room for error anywhere in here that I see.

**`.github/workflows/size-limit.yml`:**

```yml
name: size
on:
  pull_request:
    branches:
      - master
jobs:
  size:
    runs-on: ubuntu-latest
    env:
      CI_JOB_NUMBER: 1
      NODE_OPTIONS: "--max-old-space-size=4096"
    steps:
      - uses: actions/checkout@v2

      - uses: pnpm/action-setup@v4
        with:
          version: 9.8.0

      - uses: andresz1/size-limit-action@v1.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          directory: apps/platform
          package_manager: pnpm
```

**`package.json`:**

```json
"scripts": {
  "build": "vite build",
  "size": "size-limit"
},
"size-limit": [
  {
    "limit": "1.25 MB",
    "path": "dist/assets/main-*.js"
  }
],
```

The GHA output shows that it's not calculating values of 0 for the PR branch or the master branch:

```
/usr/local/bin/npx size-limit --json
[
  {
    "name": "dist/assets/main-ByafeW4Z.js",
    "passed": true,
    "size": 718406,
    "sizeLimit": 1250000,
    "running": 0.14495333333333332,
    "loading": 14.0313671875
  }
]

[...SNIP...]

Previous HEAD position was 99f0b03 Merge 60224dbce07cb8d52a9581bea2c8e44d0561b8a1 into 941eb9fe475526a764a070a9238bc086099da0ff
Switched to a new branch 'master'
branch 'master' set up to track 'origin/master'.

[...SNIP...]

/usr/local/bin/npx size-limit --json
[
  {
    "name": "dist/assets/main-h8VYuD4J.js",
    "passed": true,
    "size": 658795,
    "sizeLimit": 1250000,
    "running": 0.1[179](https://github.com/XXX/XXX/actions/runs/13461514713/job/37617763814?pr=2633#step:4:180)7999999999999,
    "loading": 12.86708984375
  }
]
```

Is there something I've got configured wrong somewhere in here?
