### ISSUE TITLE
Action always installs packages, even with `skip_step: install`

### ISSUE THREAD

**Issue by Torathion** [andresz1/size-limit-action#124]
With this configuration

```yaml
            - name: Build size report
              uses: andresz1/size-limit-action@v1
              with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                skip_step: install
                script: pnpm run size
                directory: ./dist
                package_manager: pnpm
```

it leads to this crash:

![Image](https://github.com/user-attachments/assets/38ebee55-8379-4640-91e3-c1bbb99000e4)

Also, for some reason, it doesn't understand projects that both support an ESM and CJS build.
