### ISSUE TITLE
Different size-limit results without any code changes

### ISSUE THREAD

**Issue by bobaaaaa** [andresz1/size-limit-action#31]
Hi, this is not be a blaming issues. I only want to understand why this could happen.

## size-limit config

```json
"size-limit": [
    {
      "name": "Global Critical CSS",
      "limit": "14 kb",
      "path": "apps/web/.next/static/css/*.css",
      "webpack": false
    },
    {
      "name": "First Load JS (shared by all pages)",
      "limit": "170 kb",
      "path": [
        "apps/web/.next/static/chunks/*.js",
        "apps/web/.next/static/runtime/*.js"
      ],
      "webpack": false
    }
  ],
```

## gh action

> info: yarn install without any postinstall stuff

```yml
  size:
    name: Size-limit
    runs-on: ubuntu-18.04
    env:
      CI: true

    steps:
      - name: Checkout PR
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          registry-url: 'https://npm.pkg.github.com'

      - name: Setup yarn cache
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Restore cache
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install
        run: yarn install --frozen-lockfile
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run size-limit check
        uses: andresz1/size-limit-action@v1.4.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
```

## Run

I created a PR without any source code changes (only README to trigger CI). I get the following results via gh actions console:

### PR result

```
[
  {
    "name": "Global Critical CSS",
    "passed": true,
    "size": 4567,
    "running": 0,
    "loading": 0.08919921875
  },
  {
    "name": "First Load JS (shared by all pages)",
    "passed": true,
    "size": 102933,
    "running": 2.95075,
    "loading": 2.01041015625
  }
]
```

### master result

```
[
  {
    "name": "Global Critical CSS",
    "passed": true,
    "size": 4567,
    "running": 0,
    "loading": 0.08919921875
  },
  {
    "name": "First Load JS (shared by all pages)",
    "passed": true,
    "size": 132073,
    "running": 3.9201799999999998,
    "loading": 2.57955078125
  }
]
```

### local size-limit run

```
  Global Critical CSS
  Size limit:   14 KB
  Size:         4.46 KB with all dependencies, minified and gzipped
  Loading time: 90 ms   on slow 3G
  Running time: 0 ms    on Snapdragon 410
  Total time:   90 ms
  
  First Load JS (shared by all pages)
  Size limit:   170 KB
  Size:         100.52 KB with all dependencies, minified and gzipped
  Loading time: 2.1 s     on slow 3G
  Running time: 821 ms    on Snapdragon 410
  Total time:   2.9 s
```

## Question

I don't care about the `running` and `loading` timings but the js `size` changed from `102933` to `132073`. What could be the reason for that? Did I configure something totally wrong? Or is this just an issue for `size-limit` itself? Thanks for the help. Really appreciate the work on this action ❤️
