### ISSUE TITLE
How to use with code splitting?

### ISSUE THREAD

**Issue by stereobooster** [andresz1/size-limit-action#61]
Hi, thanks for creating this action. I wonder how to use with code splitting (create react app)

I get report like this:

| Path                                                                                                                  | Size                 |
| --------------------------------------------------------------------------------------------------------------------- | -------------------- |
| build/static/js/2.77974caf.chunk.js, build/static/js/main.752b1db4.chunk.js, build/static/js/runtime-main.0ae10436.js | 0 B (-100% 🔽)       |
| build/static/js/2.e9c79fc7.chunk.js, build/static/js/main.507c610f.chunk.js, build/static/js/runtime-main.0ae10436.js | 267.79 KB (+100% 🔺) |

which is not very useful (in reality the difference is 16kb).

```json
  "size-limit": [
    {
      "path": "build/static/js/*.chunk.js"
    }
  ]
```

**Comment by stereobooster** [comment]
```yaml
    - uses: preactjs/compressed-size-action@v2
      with:
        pattern: "build/static/js/*.js"
        strip-hash: "\\b\\w{8}\\."
```
