### ISSUE TITLE
Wrong docs or build command?

### ISSUE THREAD

**Issue by Drapegnik** [andresz1/size-limit-action#68]
## According to docs:
> By default this action will try to build your PR by running `build` npm script located in your package.json. If something need to be done after dependencies are installed but before building postinstall npm script could be used

## Actually
action try to run `size-build` script

```
/usr/local/bin/npm run size-build
npm ERR! missing script: size-build
npm ERR! 
npm ERR! Did you mean one of these?
npm ERR!     build
npm ERR!     size-limit
```

https://github.com/realtby/icons/runs/4328185529?check_suite_focus=true#step:3:30

workflow:
```
name: 'size'
on:
  pull_request:
    branches:
      - main
jobs:
  size:
    runs-on: ubuntu-latest
    env:
      CI_JOB_NUMBER: 1
    steps:
      - uses: actions/checkout@v1
      - uses: andresz1/size-limit-action@v1.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
```
