### ISSUE TITLE
Feature Request: Install Settings

### ISSUE THREAD

**Issue by prescottprue** [andresz1/size-limit-action#7]
It would be awesome if there was a settings for the install that is called [on this line](https://github.com/andresz1/size-limit-action/blob/8e1a88d1e13b83dae3a8108b88282261e39ccaa2/src/Git.ts#L13) including the ability to turn off, or use yarn.

Planning on having this run after my build and install has already happened within the workflow, but without the option to turn off install dependencies are installed twice. When using in a repo with yarn, the second install fails since it tries to use npm.

Something like `install` would work nice:

```yaml
- name: Size Check
  uses: andresz1/size-limit-action@v1.0.0
  env:
    CI_JOB_NUMBER: 1
  with:
    install: false # skip running of npm install
    github_token: ${{ secrets.GITHUB_TOKEN }}
```

For those who want to run the install using yarn, maybe something like `useYarn`:

```yaml
- name: Size Check
  uses: andresz1/size-limit-action@v1.0.0
  env:
    CI_JOB_NUMBER: 1
  with:
    useYarn: true # use yarn to install instead of npm
    github_token: ${{ secrets.GITHUB_TOKEN }}
```

I'll try to make a PR soon
